name: Catalgo Service

on:
    push:
        paths:
            - 'catalog-service/**'
        branches:
            - '**'

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        env:
          working-directory: ./catalog-service
        defaults:
          working-directory: ${{ env.working-directory }}
        steps:
            - uses: actions/checkout@v3
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'temurin'
                  cache: maven

            - name: Build with Maven
              run: ./mvnw -ntp verify

